// <auto-generated />

using System.ComponentModel;
namespace crmUGWorkflow.ProxyClasses
{
    public enum eAccount_preferredappointmenttimecode
    {
        /// <summary>
        /// <para>Morning</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Morning")]
        Morning = 1,

        /// <summary>
        /// <para>Afternoon</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Afternoon")]
        Afternoon = 2,

        /// <summary>
        /// <para>Evening</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Evening")]
        Evening = 3,
    }
}
