// <auto-generated />

using System.ComponentModel;
namespace crmUGWorkflow.ProxyClasses
{
    public enum eIncident_caseorigincode
    {
        /// <summary>
        /// <para>Phone</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Phone")]
        Phone = 1,

        /// <summary>
        /// <para>Email</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Email")]
        Email = 2,

        /// <summary>
        /// <para>Web</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Web")]
        Web = 3,

        /// <summary>
        /// <para>Facebook</para>
        /// <para>Value = 2483</para>
        /// </summary>
        [Description("Facebook")]
        Facebook = 2483,

        /// <summary>
        /// <para>Twitter</para>
        /// <para>Value = 3986</para>
        /// </summary>
        [Description("Twitter")]
        Twitter = 3986,
    }
}
