// <auto-generated />

using System.ComponentModel;
namespace crmUGWorkflow.ProxyClasses
{
    public enum eIncident_contractservicelevelcode
    {
        /// <summary>
        /// <para>Gold</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Gold")]
        Gold = 1,

        /// <summary>
        /// <para>Silver</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Silver")]
        Silver = 2,

        /// <summary>
        /// <para>Bronze</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Bronze")]
        Bronze = 3,
    }
}
