// <auto-generated />

using System.ComponentModel;
namespace crmUGWorkflow.ProxyClasses
{
    public enum eIncident_casetypecode
    {
        /// <summary>
        /// <para>Question</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Question")]
        Question = 1,

        /// <summary>
        /// <para>Problem</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Problem")]
        Problem = 2,

        /// <summary>
        /// <para>Request</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Request")]
        Request = 3,
    }
}
