// <auto-generated />

using System.ComponentModel;
namespace crmUGWorkflow.ProxyClasses
{
    public enum eIncident_prioritycode
    {
        /// <summary>
        /// <para>High</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("High")]
        High = 1,

        /// <summary>
        /// <para>Normal</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Normal")]
        Normal = 2,

        /// <summary>
        /// <para>Low</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Low")]
        Low = 3,
    }
}
