// <auto-generated />

using System.ComponentModel;
namespace crmUGWorkflow.ProxyClasses
{
    public enum eIncident_statuscode
    {
        /// <summary>
        /// <para>Problem Solved</para>
        /// <para>Value = 5</para>
        /// </summary>
        [Description("Problem Solved")]
        ProblemSolved = 5,

        /// <summary>
        /// <para>Information Provided</para>
        /// <para>Value = 1000</para>
        /// </summary>
        [Description("Information Provided")]
        InformationProvided = 1000,

        /// <summary>
        /// <para>Cancelled</para>
        /// <para>Value = 6</para>
        /// </summary>
        [Description("Cancelled")]
        Cancelled = 6,

        /// <summary>
        /// <para>Merged</para>
        /// <para>Value = 2000</para>
        /// </summary>
        [Description("Merged")]
        Merged = 2000,

        /// <summary>
        /// <para>In Progress</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("In Progress")]
        InProgress = 1,

        /// <summary>
        /// <para>On Hold</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("On Hold")]
        OnHold = 2,

        /// <summary>
        /// <para>Waiting for Details</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Waiting for Details")]
        WaitingForDetails = 3,

        /// <summary>
        /// <para>Researching</para>
        /// <para>Value = 4</para>
        /// </summary>
        [Description("Researching")]
        Researching = 4,
    }
}
