// <auto-generated />

using System.ComponentModel;
namespace crmUGWorkflow.ProxyClasses
{
    public enum eIncident_statecode
    {
        /// <summary>
        /// <para>Active</para>
        /// <para>Value = 0</para>
        /// </summary>
        [Description("Active")]
        Active = 0,

        /// <summary>
        /// <para>Resolved</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Resolved")]
        Resolved = 1,

        /// <summary>
        /// <para>Cancelled</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Cancelled")]
        Cancelled = 2,
    }
}
