// <auto-generated />

using System.ComponentModel;
namespace crmUGWorkflow.ProxyClasses
{
    public enum eIncident_resolvebyslastatus
    {
        /// <summary>
        /// <para>In Progress</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("In Progress")]
        InProgress = 1,

        /// <summary>
        /// <para>Nearing Noncompliance</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Nearing Noncompliance")]
        NearingNoncompliance = 2,

        /// <summary>
        /// <para>Succeeded</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Succeeded")]
        Succeeded = 3,

        /// <summary>
        /// <para>Noncompliant</para>
        /// <para>Value = 4</para>
        /// </summary>
        [Description("Noncompliant")]
        Noncompliant = 4,
    }
}
