// <auto-generated />

using System.ComponentModel;
namespace crmUGWorkflow.ProxyClasses
{
    public enum eIncident_customersatisfactioncode
    {
        /// <summary>
        /// <para>Very Satisfied</para>
        /// <para>Value = 5</para>
        /// </summary>
        [Description("Very Satisfied")]
        VerySatisfied = 5,

        /// <summary>
        /// <para>Satisfied</para>
        /// <para>Value = 4</para>
        /// </summary>
        [Description("Satisfied")]
        Satisfied = 4,

        /// <summary>
        /// <para>Neutral</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Neutral")]
        Neutral = 3,

        /// <summary>
        /// <para>Dissatisfied</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Dissatisfied")]
        Dissatisfied = 2,

        /// <summary>
        /// <para>Very Dissatisfied</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Very Dissatisfied")]
        VeryDissatisfied = 1,
    }
}
