// <auto-generated />

using System.ComponentModel;
namespace crmUGWorkflow.ProxyClasses
{
    public enum eServicestage
    {
        /// <summary>
        /// <para>Identify</para>
        /// <para>Value = 0</para>
        /// </summary>
        [Description("Identify")]
        Identify = 0,

        /// <summary>
        /// <para>Research</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Research")]
        Research = 1,

        /// <summary>
        /// <para>Resolve</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Resolve")]
        Resolve = 2,
    }
}
