// <auto-generated />

using System.ComponentModel;
namespace crmUGWorkflow.ProxyClasses
{
    public enum eSocialactivity_postmessagetype
    {
        /// <summary>
        /// <para>Public Message</para>
        /// <para>Value = 0</para>
        /// </summary>
        [Description("Public Message")]
        PublicMessage = 0,

        /// <summary>
        /// <para>Private Message</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Private Message")]
        PrivateMessage = 1,
    }
}
